### PR TITLE
Add sidekiq logs

### PR DESCRIPTION
**Pull request by EdHurtig**
Adds tracking, groking, and filtering of sidekiq logs to the ELK Rigs

ELK Rigs

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
Mad props for image search game

**Comment by EdHurtig** [comment]
Image search game was strong on this one

**Comment by jeffbyrnes** [comment]
@EdHurtig any reason we shouldn’t ship this now? Other than the fact that you’ll also have to tackle [PLATFORM-1025](https://evertroops.atlassian.net/browse/PLATFORM-1025) to even get it out in the wild, that is.

**Comment by EdHurtig** [comment]
uhhh... untested... will see if I can get this in a ship-able state

**Pull request merged**
