### PR TITLE
Fix some minor convergence issues

### PR DESCRIPTION
**Pull request by eherot**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
LGTM :shipit:

**Comment by jeffbyrnes** [comment]
Failing tests are RuboCop being a jerk.

**Comment by jeffbyrnes** [comment]
@eherot I rebased this to try to get it to work, but it seems things have changed since then, and now Berkshelf can’t solve the dependencies. Not sure where the conflict is.

**Comment by eherot** [comment]
Deleting Berksfile.lock and switching to the master branch version of Berkshelf seemed to work.

**Comment by jeffbyrnes** [comment]
@eherot really? Fascinating. Any idea when they’re shipping that new depsolver?

**Comment by eherot** [comment]
heh, nope, but it's way better.

**Pull request merged**
